/**
 * LaTeX résumé source.
 *
 * Most technical candidates keep their résumé in LaTeX, and the value of that
 * is twofold: it typesets well, and it is editable in Overleaf. This produces
 * the source, which delivers both — rather than compiling server-side, which
 * would mean shipping a TeX distribution that cannot run on serverless and
 * would add seconds to every application.
 *
 * ## Why the layout is plain
 *
 * Single column, no tables, no multi-column headers. The elaborate templates
 * look better to a human and parse worse in an applicant tracking system:
 * column layouts get read in the wrong order and the résumé arrives scrambled.
 * This follows the single-column convention, which survives both readers.
 *
 * The document compiles with pdflatex against a stock TeX Live — only
 * `geometry`, `enumitem`, `titlesec` and `hyperref`, all standard — so it
 * opens in Overleaf with nothing to install.
 */

const BACKSLASH = String.fromCharCode(92);

/**
 * Escape the characters TeX treats as syntax.
 *
 * Ordering is the whole difficulty. The replacements for backslash, tilde and
 * caret are themselves commands containing braces, so running the brace pass
 * after them re-escapes the braces they just introduced and emits
 * `\textbackslash\{\}` — which does not compile, and the candidate only finds
 * out in Overleaf. Sentinels stand in until the brace pass is done.
 */
function esc(s: string): string {
  const MARK = '\u0000';
  return s
    .split(BACKSLASH)
    .join(`${MARK}bs${MARK}`)
    .replace(/~/g, `${MARK}tilde${MARK}`)
    .replace(/\^/g, `${MARK}caret${MARK}`)
    .replace(/([&%$#_{}])/g, `${BACKSLASH}$1`)
    .replace(new RegExp(`${MARK}bs${MARK}`, 'g'), `${BACKSLASH}textbackslash{}`)
    .replace(new RegExp(`${MARK}tilde${MARK}`, 'g'), `${BACKSLASH}textasciitilde{}`)
    .replace(new RegExp(`${MARK}caret${MARK}`, 'g'), `${BACKSLASH}textasciicircum{}`);
}

export type LatexOptions = {
  name?: string;
  email?: string;
  phone?: string;
  website?: string;
  /** Points. 10 to 11 is the readable range for a résumé. */
  fontSize?: number;
};

type Block = { heading: string; lines: string[] };

/**
 * Split plain text into headings and their content.
 *
 * A heading is a short line in capitals or ending in a colon — the convention
 * résumés already follow, so a document the candidate pasted in keeps its
 * structure instead of becoming one undifferentiated block.
 */
function parse(text: string): Block[] {
  const blocks: Block[] = [];
  let current: Block | null = null;

  for (const raw of text.replace(/\r\n?/g, '\n').split('\n')) {
    const line = raw.trim();
    if (!line) continue;

    const isHeading = line.length < 48 && (/^[A-Z][A-Z\s&/-]{2,}$/.test(line) || line.endsWith(':'));

    if (isHeading) {
      current = { heading: line.replace(/:$/, ''), lines: [] };
      blocks.push(current);
      continue;
    }
    if (!current) {
      current = { heading: '', lines: [] };
      blocks.push(current);
    }
    current.lines.push(line);
  }
  return blocks;
}

export function toLatex(text: string, options: LatexOptions = {}): string {
  const B = BACKSLASH;
  const size = Math.round(options.fontSize ?? 11);
  const blocks = parse(text);

  const contact = [options.email, options.phone, options.website]
    .filter(Boolean)
    .map((v) => esc(String(v)))
    .join(` $|$ `);

  const body = blocks
    .map((b) => {
      /* Lines opening with a bullet marker become an itemize; the rest stay as
         paragraphs, so prose is not forced into a list it never was. */
      const bullets = b.lines.filter((l) => /^[-•*]\s+/.test(l));
      const prose = b.lines.filter((l) => !/^[-•*]\s+/.test(l));

      const parts: string[] = [];
      if (b.heading) parts.push(`${B}section{${esc(b.heading)}}`);
      for (const p of prose) parts.push(`${esc(p)}\n`);
      if (bullets.length > 0) {
        parts.push(`${B}begin{itemize}[leftmargin=*, itemsep=1pt, topsep=2pt]`);
        for (const item of bullets) parts.push(`  ${B}item ${esc(item.replace(/^[-•*]\s+/, ''))}`);
        parts.push(`${B}end{itemize}`);
      }
      return parts.join('\n');
    })
    .join('\n\n');

  const header = options.name ? `{${B}LARGE${B}bfseries ${esc(options.name)}}` : '';
  const contactLine = contact ? `${B}${B}[3pt]\n  ${contact}` : '';

  return [
    `% Generated by MeritFlow. Compiles with pdflatex on a stock TeX Live.`,
    `% Single column and no tables on purpose: multi-column resumes are read`,
    `% out of order by applicant tracking systems and arrive scrambled.`,
    `${B}documentclass[${size}pt,letterpaper]{article}`,
    ``,
    `${B}usepackage[margin=0.75in]{geometry}`,
    `${B}usepackage{enumitem}`,
    `${B}usepackage{titlesec}`,
    `${B}usepackage[hidelinks]{hyperref}`,
    ``,
    `${B}pagestyle{empty}`,
    `${B}setlength{${B}parindent}{0pt}`,
    `${B}setlength{${B}parskip}{4pt}`,
    ``,
    `% A rule under each heading: the convention, and free in parseability.`,
    `${B}titleformat{${B}section}{${B}large${B}bfseries${B}uppercase}{}{0em}{}[${B}titlerule]`,
    `${B}titlespacing{${B}section}{0pt}{10pt}{4pt}`,
    ``,
    `${B}begin{document}`,
    ``,
    `${B}begin{center}`,
    `  ${header}${contactLine}`,
    `${B}end{center}`,
    ``,
    body,
    ``,
    `${B}end{document}`,
    ``,
  ].join('\n');
}

/**
 * Where Overleaf accepts a project.
 *
 * Submitted as a form POST rather than a link, because a GET carrying a whole
 * résumé in the query string exceeds what browsers and proxies will pass.
 */
export const OVERLEAF_ENDPOINT = 'https://www.overleaf.com/docs';
