import { loadEnv } from './env';
loadEnv();
import { getDb } from '../src/lib/db';
async function main(): Promise<void> {
  const db = await getDb();
  const u = await db.query<{ id: string }>('SELECT id FROM users WHERE lower(email) = $1', [process.argv[2].toLowerCase()]);
  const r = await db.query<{ company: string; title: string; receipt: string; updated_at: number }>(
    "SELECT j.company, j.title, a.receipt, a.updated_at FROM autopilot_runs a JOIN jobs j ON j.id=a.job_id WHERE a.user_id=$1 AND a.state='SUBMITTED' ORDER BY a.updated_at", [u.rows[0].id]);
  for (const row of r.rows) {
    const rec = JSON.parse(row.receipt) as { confirmation?: { reference: string; evidence?: string[] } };
    const ref = rec.confirmation?.reference ?? '(none)';
    const generated = /^(greenhouse|lever|ashby|generic)-[a-z0-9]+$/i.test(ref);
    process.stdout.write(`${row.company} — ${row.title.slice(0,44)}\n`);
    process.stdout.write(`  sent      ${new Date(row.updated_at).toLocaleString()}\n`);
    process.stdout.write(`  reference ${ref} ${generated ? '(generated by us, not the employer)' : '(from the employer)'}\n`);
    process.stdout.write(`  evidence  ${JSON.stringify(rec.confirmation?.evidence ?? [])}\n\n`);
  }
  process.exit(0);
}
void main().catch((e: unknown) => { process.stderr.write(String(e) + '\n'); process.exit(1); });
